#!/usr/bin/perl -w

use strict;
use utf8;
use warnings;

use DB_File;
use DBM_Filter;

my (%Disambs);

die unless (@ARGV == 2);

open (DISAMBS, '<:encoding(UTF-8)', $ARGV [0]) or die ($!);

# Set up databases.
chmod (0664, $ARGV [1]);
my $db_d = tie (%Disambs, 'DB_File', $ARGV [1], O_CREAT | O_RDWR, 0666, $DB_BTREE);
$db_d->Filter_Push ('utf8');
%Disambs = ('#' => (stat (DISAMBS)) [9]);

while (defined (my $line = <DISAMBS>))
  {
    $line =~ s/^(.*)\n// or die;
    $Disambs {$1} = 1;
  }

# Close databases.
undef $db_d;
untie (%Disambs);
chmod (0444, $ARGV [1]);
close (DISAMBS);
