#!/usr/bin/perl -w

use strict;
use utf8;
use warnings;

use DB_File;
use DBM_Filter;

my (%Redirs);

die unless (@ARGV == 2);

open (REDIRS, '<:encoding(UTF-8)', $ARGV [0]) or die ($!);

# Set up databases.
chmod (0664, $ARGV [1]);
my $db_d = tie (%Redirs, 'DB_File', $ARGV [1], O_CREAT | O_RDWR, 0666, $DB_BTREE);
$db_d->Filter_Push ('utf8');
%Redirs = ('#' => (stat (REDIRS)) [9]);

while (defined (my $line = <REDIRS>))
  {
    next if ($. == 1 || $. % 2 == 0);
    $line =~ /^(.*)\t(.*)\n$/ || die;
    $Redirs {$1} = $2;
  }

# Close databases.
undef $db_d;
untie (%Redirs);
chmod (0444, $ARGV [1]);
close (REDIRS);
