#!/usr/bin/perl -w

use strict;
use utf8;
use warnings;

use DBI;

die unless (@ARGV == 3);

# Set up database.
my $DB = DBI->connect ('dbi:SQLite:dbname=' . $ARGV [0], '', '', {AutoCommit => 0, PrintError => 0, unicode => 1}) or die (DBI->errstr ());

# $DB->begin_work () or die ($DB->errstr ());

if (!$DB->do ('DELETE FROM DisambiguationPages;')                                   &&
    !$DB->do ('CREATE TABLE DisambiguationPages (Title VARCHAR(255) PRIMARY KEY);'))
  { die ($DB->errstr ()); }

if (!$DB->do ('DELETE FROM Redirects;')                                                                        &&
    !($DB->do ('CREATE TABLE Redirects (FromTitle VARCHAR(255) PRIMARY KEY, ToTitle VARCHAR(255) NOT NULL);') &&
      $DB->do ('CREATE INDEX Redirects_ToTitle_Index ON Redirects (ToTitle);')))
  { die ($DB->errstr ()); }

# Disambiguation pages.
open (DISAMBS, '<:encoding(UTF-8)', $ARGV [1]) or die ($!);
my $s = $DB->prepare ('INSERT INTO DisambiguationPages (Title) VALUES (?);') or die ($DB->errstr ());
$s->execute ('#' . (stat (DISAMBS)) [9]) or die ($DB->errstr ());
while (<DISAMBS>)
  {
    chomp ();
    $s->execute ($_) or die ($DB->errstr ());
  }
close (DISAMBS);

# Redirects.
open (REDIRECTS, '<:encoding(UTF-8)', $ARGV [2]) or die ($!);
$s = $DB->prepare ('INSERT INTO Redirects (FromTitle, ToTitle) VALUES (?, ?);') or die ($DB->errstr ());
$s->execute ('#', (stat (REDIRECTS)) [9]) or die ($DB->errstr ());
while (<REDIRECTS>)
  {
    /^([^\t]+)\t([^\t]+)\n/ or die;
    $s->execute ($1, $2) or die ($DB->errstr ());
  }
close (REDIRECTS);

# Close database.
$DB->commit () or die ($DB->errstr ());
$DB->disconnect ();
