---
name: wikilint
version: 0.1
author:
  - 'Tim Landscheidt <tim@tim-landscheidt.de>'
abstract: A web based service to find errors (like typos and wrong formatting) in Wikipedia articles and make proposals how to improve them.
license: gpl
resources:
  license: ~
requires:
  CGI: 0
  DBD::SQLite: 0
  DBI: 0
  HTML::Entities: 0
  LWP::UserAgent: 0
  URI::Escape: 0
build_requires:
  App::Build: 0
  DBD::SQLite: 0
dynamic_config: 1
provides:
  Wikilint:
    file: lib/Wikilint.pm
  Wikilint::Config:
    file: lib/Wikilint/Config.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
